[package]
name = "cellang-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4", features = ["derive"] }
miette = { version="^7", features = ["fancy"] }
cellang = { path = "../lib" }
serde_json = "^1"
