use crate::handlers::MethodNotSupportedHandler;
use crate::server::ServerCore;
use serde_json::Value;
use wasm_bindgen::prelude::*;

/// WASM bridge that accepts JSON-RPC payload strings and returns outbound
/// messages generated by the LSP core.
#[wasm_bindgen]
pub struct WasmHostBridge {
    core: ServerCore<MethodNotSupportedHandler>,
}

#[wasm_bindgen]
impl WasmHostBridge {
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        Self {
            core: ServerCore::new(MethodNotSupportedHandler),
        }
    }

    /// Dispatches one inbound JSON-RPC message into `ServerCore` and returns
    /// all outbound responses/notifications as JSON strings.
    #[wasm_bindgen(js_name = "handleMessage")]
    pub fn handle_message(
        &mut self,
        message: &str,
    ) -> Result<Vec<String>, JsValue> {
        let payload: Value = serde_json::from_str(message).map_err(|err| {
            JsValue::from(format!("invalid JSON-RPC payload: {err}"))
        })?;

        self.core
            .handle_payload(payload)
            .into_iter()
            .map(|outbound| {
                serde_json::to_string(&outbound).map_err(|err| {
                    JsValue::from(format!(
                        "failed to serialize outbound JSON-RPC payload: {err}"
                    ))
                })
            })
            .collect()
    }
}

impl Default for WasmHostBridge {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn parse_messages(messages: &[String]) -> Vec<Value> {
        messages
            .iter()
            .map(|payload| {
                serde_json::from_str(payload).expect("valid outbound json")
            })
            .collect()
    }

    #[test]
    fn handle_message_returns_publish_diagnostics_for_open_notification() {
        let mut bridge = WasmHostBridge::new();

        let inbound = json!({
            "jsonrpc": "2.0",
            "method": "textDocument/didOpen",
            "params": {
                "textDocument": {
                    "uri": "file:///workspace/adapter.cel",
                    "languageId": "cellang",
                    "version": 1,
                    "text": "1 + )"
                }
            }
        });

        let outbounds = bridge
            .handle_message(&inbound.to_string())
            .expect("dispatch succeeds");
        assert_eq!(outbounds.len(), 1, "didOpen should emit diagnostics");

        let parsed = parse_messages(&outbounds);
        assert_eq!(
            parsed[0].pointer("/method").and_then(Value::as_str),
            Some("textDocument/publishDiagnostics")
        );
        assert_eq!(
            parsed[0].pointer("/params/uri").and_then(Value::as_str),
            Some("file:///workspace/adapter.cel")
        );
    }

    #[test]
    fn handle_message_supports_stateful_request_response_flow() {
        let mut bridge = WasmHostBridge::new();

        let open = json!({
            "jsonrpc": "2.0",
            "method": "textDocument/didOpen",
            "params": {
                "textDocument": {
                    "uri": "file:///workspace/def_ref.cel",
                    "languageId": "cellang",
                    "version": 1,
                    "text": "roles.exists(role, role == target)"
                }
            }
        });

        let _ = bridge
            .handle_message(&open.to_string())
            .expect("open succeeds");

        let definition = json!({
            "jsonrpc": "2.0",
            "id": 7,
            "method": "textDocument/definition",
            "params": {
                "textDocument": { "uri": "file:///workspace/def_ref.cel" },
                "position": { "line": 0, "character": 20 }
            }
        });

        let outbounds = bridge
            .handle_message(&definition.to_string())
            .expect("definition dispatch succeeds");
        assert_eq!(outbounds.len(), 1);

        let parsed = parse_messages(&outbounds);
        assert_eq!(parsed[0].pointer("/id").and_then(Value::as_i64), Some(7));
        assert!(
            parsed[0].pointer("/result").is_some(),
            "request should produce JSON-RPC result field"
        );
    }

    #[test]
    fn handle_message_rejects_invalid_json_payload() {
        let mut bridge = WasmHostBridge::new();
        let error = bridge
            .handle_message("{not valid json}")
            .expect_err("invalid payload must fail");
        let message = error.as_string().expect("error as string");
        assert!(message.contains("invalid JSON-RPC payload"));
    }
}
